1. Panel data or Python Data Analysis
1. series and data frame
1. load, manipulate, prepare, model, and analyze data
1. df.sort_values('column name, inplace=True)
1. text file format that uses commas to separate values
1. nulls, duplicates, outliers 

In [9]:
#7 & #12
import numpy as np

array = np.arange(12)
reshapedArray = array.reshape(2,3,2)

print(reshapedArray)







[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [10]:
#8 Use NumPy .linspace() to create an array with 6 linearly spaced values between 0 and 20
#9 Make a Deep Copy of the above array

import numpy as np

np.linspace(0, 20, num=6)



import copy

newnp = np.linspace(0, 20, num=6)
newnp2 = copy.deepcopy(newnp)
print(newnp2)


[ 0.  4.  8. 12. 16. 20.]


In [11]:
#10 & #11
import numpy as np

array1 = np.array([[25, 16]])
array2 = np.array([[11,2], [13,4]])
array3 = np.array([[7,81], [5,6], [11,12]])

newArray = np.concatenate((array1, array2, array3), axis=0)
print(newArray)

sortedArray = np.sort(newArray, axis=0)

print(sortedArray)


[[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]
[[ 5  2]
 [ 7  4]
 [11  6]
 [11 12]
 [13 16]
 [25 81]]


In [12]:
reshapedArray = np.array([(5,2), (7,4), (11,6), (11,12)])

tup1, tup2, tup3, tup4 = reshapedArray

print("First Variable: ", tup1)
print("Second Variable: ", tup2)
print("Third Variable: ", tup3)
print("Fourth Variable: ", tup4)

First Variable:  [5 2]
Second Variable:  [7 4]
Third Variable:  [11  6]
Fourth Variable:  [11 12]


In [13]:
#13 Combined and sort the following arrays into one called 'comboArray' 
import numpy as np

one = ([10, 11, 12, 13, 14, 15, 16, 17])
two = ([20, 21, 22, 23, 24, 25, 26, 27])
three = ([ 0, 1, 2, 3, 4, 5, 6, 7])

comboArray = np.concatenate((one, two, three), axis=0)

comboArray = np.sort(comboArray)
print(comboArray)

#14
print(comboArray[1:2])
print(comboArray[2:])
print(comboArray[3:14])
print(comboArray[18:])
print(comboArray[:-9])
print(comboArray[20:25:2]) #23
print(comboArray[::-5])

[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
[1]
[ 2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
[ 3  4  5  6  7 10 11 12 13 14 15]
[22 23 24 25 26 27]
[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16]
[24 26]
[27 22 15 10  3]


In [14]:
#15
import numpy as np
import pandas as pd

Ingredients = pd.Series(["Flour", "Milk", "Eggs", "Spam"], name="Ingredients")
Quantity = pd.Series([4, 1, 2, 1],name="Quantity")
Unit = pd.Series(["cups", "cup", "large", "can"], name="Unit")

dataframe = pd.concat([Ingredients, Quantity, Unit], axis=1)
dataframe




Ingredients  Quantity   Unit
0       Flour         4   cups
1        Milk         1    cup
2        Eggs         2  large
3        Spam         1    can

In [15]:
#16
import numpy as np
import pandas as pd

studentData = pd.DataFrame({'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
        'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
        'Age': [21, 23, 24, 21],
        'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
        'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']})


df = pd.DataFrame(studentData)
df

   

Name  Height Qualification  address  Age        Pets           sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket

In [16]:
#17 
dessert = ["Ice Cream", "Cashew Fudge", "Waffles", "Carrot Halwa"]


df["Desserts"] = dessert

df



Name  Height Qualification  address  Age        Pets           sport  \
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   

       Desserts  
0     Ice Cream  
1  Cashew Fudge  
2       Waffles  
3  Carrot Halwa

In [17]:
#18
df.sort_values(by=["Name", "address"], inplace=True)
df



Name  Height Qualification  address  Age        Pets           sport  \
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   

       Desserts  
3  Carrot Halwa  
2       Waffles  
0     Ice Cream  
1  Cashew Fudge

In [25]:
#19
import pandas as pd

cows_and_goats = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])

cows_and_goats

cows_and_goats.to_csv("cows_and_goats.csv")

df = pd.read_csv("cows_and_goats.csv")
print(df)

  Unnamed: 0  Cows  Goats
0     Year 1    12     22
1     Year 2    20     19


In [ ]:
#20 A)
import pandas as pd

vegetables = pd.DataFrame([["Broccoli", "Green"], ["Carrots", "Orange"], ["Beets", "Purple"], ["Squash", "Yellow"]],
                            columns=["Vegetable", "Color"])

vegetables

vegetables.to_csv("vegetables.csv", index=False)

df = pd.read_csv("vegetables.csv")
print(df)





  Vegetable   Color
0  Broccoli   Green
1   Carrots  Orange
2     Beets  Purple
3    Squash  Yellow


In [23]:
#20 B)
#Using Pandas, make a change to your CSV file, and save a copy with a different names

import pandas as pd
vegetables = pd.read_csv('vegetables.csv')

packages = ["20","30", "18", "16"]

vegetables.insert(2, "Packages", packages, True)


vegetables.to_csv("newvegetables.csv", index=False)

df = pd.read_csv('newvegetables.csv')
print(df)

  Vegetable   Color  Packages
0  Broccoli   Green        20
1   Carrots  Orange        30
2     Beets  Purple        18
3    Squash  Yellow        16
