1. Panel data or Python Data Analysis
1. series and data frame
1. load, manipulate, prepare, model, and analyze data
1. df.sort_values()
1. text file format that uses commas to separate values
1. nulls

In [29]:
#7 & #12
import numpy as np

array = np.arange(12)

reshapedArray = array.reshape(2,3,2)

print(reshapedArray)

a, b, c, d = reshapedArray

print("a = ", a)
print("b = ", b)
print("c = ", c)
print("d = ", d)

# I know I did this wrong because I only have 2 arrays and idk what to do 

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


ValueError: not enough values to unpack (expected 4, got 2)

In [ ]:
#8 Use NumPy .linspace() to create an array with 6 linearly spaced values between 0 and 20
#9 Make a Deep Copy of the above array

import numpy as np

np.linspace(0, 20, num=6)



import copy

newnp = np.linspace(0, 20, num=6)
newnp2 = copy.deepcopy(newnp)
print(newnp2)


[ 0.  4.  8. 12. 16. 20.]


In [ ]:
#10 & #11
import numpy as np

array1 = np.array([[25, 16]])
array2 = np.array([[11,2], [13,4]])
array3 = np.array([[7,81], [5,6], [11,12]])

newArray = np.concatenate((array1, array2, array3), axis=0)
print(newArray)

sortedArray = newArray.sort()


[[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]
None


In [ ]:
#13 Combined and sort the following arrays into one called 'comboArray' 
import numpy as np

one = ([10, 11, 12, 13, 14, 15, 16, 17])
two = ([20, 21, 22, 23, 24, 25, 26, 27])
three = ([ 0, 1, 2, 3, 4, 5, 6, 7])

comboArray = np.concatenate((one, two, three), axis=0)

comboArray = np.sort(comboArray)
print(comboArray)

#14
print(comboArray[1:2])
print(comboArray[2:])
print(comboArray[3:14])
print(comboArray[18:])
print(comboArray[:-9])
print(comboArray[20:25:2]) #23
print(comboArray[::-5])

[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
[1]
[ 2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
[ 3  4  5  6  7 10 11 12 13 14 15]
[22 23 24 25 26 27]
[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16]
[24 26]
[27 22 15 10  3]


In [ ]:
#15
import numpy as np
import pandas as pd

Ingredients = pd.Series(["Flour", "Milk", "Eggs", "Spam"], name="Ingredients")
Quantity = pd.Series([4, 1, 2, 1],name="Quantity")
Unit = pd.Series(["cups", "cup", "large", "can"], name="Unit")

dataframe = pd.concat([Ingredients, Quantity, Unit], axis=1)
dataframe




Ingredients  Quantity   Unit
0       Flour         4   cups
1        Milk         1    cup
2        Eggs         2  large
3        Spam         1    can

In [ ]:
#16
import numpy as np
import pandas as pd

studentData = {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
        'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
        'Age': [21, 23, 24, 21],
        'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
        'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']}


df = pd.DataFrame(studentData)
df

   

In [2]:
#17 
dessert = ["Ice Cream", "Cashew Fudge", "waffles", "Carrot Halwa"]


df["Desserts"] = dessert

df



Name  Height Qualification  address  Age        Pets           sport  \
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   

       Desserts  
0     Ice Cream  
1  Cashew Fudge  
2       waffles  
3  Carrot Halwa

In [14]:
#18
df.sort_values(by=['Name'], inplace=True )
df




Name  Height Qualification  address  Age        Pets           sport  \
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   

       Desserts  
2       waffles  
3  Carrot Halwa  
0     Ice Cream  
1  Cashew Fudge

In [15]:
#18
df.sort_values(by=["address"], inplace=True)
df

Name  Height Qualification  address  Age        Pets           sport  \
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   

       Desserts  
2       waffles  
3  Carrot Halwa  
0     Ice Cream  
1  Cashew Fudge

In [18]:
#19
import pandas as pd

cows_and_goats = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
cows_and_goats

cows_and_goats.to_csv("cows_and_goats.csv")

df = pd.read_csv("cows_and_goats.csv")
print(df)

  Unnamed: 0  Cows  Goats
0     Year 1    12     22
1     Year 2    20     19


In [20]:
import pandas as pd

vegetables = pd.DataFrame(['Broccoli', 'Green Beans', 'Carrots', 'Peas', 'Lettuce'])

vegetables.to_csv("vegetables.csv")
df = pd.read_csv("vegetables.csv")

print(df)

   Unnamed: 0            0
0           0     Broccoli
1           1  Green Beans
2           2      Carrots
3           3         Peas
4           4      Lettuce
