1. Panel data or Python Data Analysis
1. series and data frame
1. load, manipulate, prepare, model, and analyze data
1. df.sort_values('column name, inplace=True)
1. text file format that uses commas to separate values
1. nulls, duplicates, outliers 

In [60]:
#7 & #12
import numpy as np

array = np.arange(12)
reshapedArray = array.reshape(2,3,2)

print(reshapedArray)







[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [ ]:
#8 Use NumPy .linspace() to create an array with 6 linearly spaced values between 0 and 20
#9 Make a Deep Copy of the above array

import numpy as np

np.linspace(0, 20, num=6)



import copy

newnp = np.linspace(0, 20, num=6)
newnp2 = copy.deepcopy(newnp)
print(newnp2)


[ 0.  4.  8. 12. 16. 20.]


In [59]:
#10 & #11
import numpy as np

array1 = np.array([[25, 16]])
array2 = np.array([[11,2], [13,4]])
array3 = np.array([[7,81], [5,6], [11,12]])

newArray = np.concatenate((array1, array2, array3), axis=0)
print(newArray)

sortedArray = np.sort(newArray, axis=0)

print(sortedArray)


[[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]
[[ 5  2]
 [ 7  4]
 [11  6]
 [11 12]
 [13 16]
 [25 81]]


In [63]:
reshapedArray = np.array([(5,2), (7,4), (11,6), (11,12)])

tup1, tup2, tup3, tup4 = reshapedArray

print("First Variable: ", tup1)
print("Second Variable: ", tup2)
print("Third Variable: ", tup3)
print("Fourth Variable: ", tup4)

First Variable:  [5 2]
Second Variable:  [7 4]
Third Variable:  [11  6]
Fourth Variable:  [11 12]


In [ ]:
#13 Combined and sort the following arrays into one called 'comboArray' 
import numpy as np

one = ([10, 11, 12, 13, 14, 15, 16, 17])
two = ([20, 21, 22, 23, 24, 25, 26, 27])
three = ([ 0, 1, 2, 3, 4, 5, 6, 7])

comboArray = np.concatenate((one, two, three), axis=0)

comboArray = np.sort(comboArray)
print(comboArray)

#14
print(comboArray[1:2])
print(comboArray[2:])
print(comboArray[3:14])
print(comboArray[18:])
print(comboArray[:-9])
print(comboArray[20:25:2]) #23
print(comboArray[::-5])

[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
[1]
[ 2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
[ 3  4  5  6  7 10 11 12 13 14 15]
[22 23 24 25 26 27]
[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16]
[24 26]
[27 22 15 10  3]


In [ ]:
#15
import numpy as np
import pandas as pd

Ingredients = pd.Series(["Flour", "Milk", "Eggs", "Spam"], name="Ingredients")
Quantity = pd.Series([4, 1, 2, 1],name="Quantity")
Unit = pd.Series(["cups", "cup", "large", "can"], name="Unit")

dataframe = pd.concat([Ingredients, Quantity, Unit], axis=1)
dataframe




Ingredients  Quantity   Unit
0       Flour         4   cups
1        Milk         1    cup
2        Eggs         2  large
3        Spam         1    can

In [48]:
#16
import numpy as np
import pandas as pd

studentData = pd.DataFrame({'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
        'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
        'Age': [21, 23, 24, 21],
        'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
        'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']})


df = pd.DataFrame(studentData)
df

   

Name  Height Qualification  address  Age        Pets           sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket

In [49]:
#17 
dessert = ["Ice Cream", "Cashew Fudge", "Waffles", "Carrot Halwa"]


df["Desserts"] = dessert

df



Name  Height Qualification  address  Age        Pets           sport  \
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   

       Desserts  
0     Ice Cream  
1  Cashew Fudge  
2       Waffles  
3  Carrot Halwa

In [51]:
#18
df.sort_values(by=["Name", "address"], inplace=True)
df



Name  Height Qualification  address  Age        Pets           sport  \
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   

       Desserts  
3  Carrot Halwa  
2       Waffles  
0     Ice Cream  
1  Cashew Fudge

In [82]:
#19
import pandas as pd

df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
df

cows_and_goats.to_csv("cows_and_goats.csv")

df = pd.read_csv("cows_and_goats.csv")
print(df)

  Unnamed: 0  Cows  Goats
0     Year 1    12     22
1     Year 2    20     19


In [107]:
#20 A)
import pandas as pd

vegetables = pd.DataFrame([["Broccoli", "Green"], ["Carrots", "Orange"], ["Beets", "Purple"], ["Squash", "Yellow"]],
                            columns=["Vegetable", "Color"])

vegetables

vegetables.to_csv("vegetables.csv")

df = pd.read_csv("vegetables.csv")
print(df)





   Unnamed: 0 Vegetable   Color
0           0  Broccoli   Green
1           1   Carrots  Orange
2           2     Beets  Purple
3           3    Squash  Yellow


In [106]:
#20 B)
#Using Pandas, make a change to your CSV file, and save a copy with a different names

import pandas as pd
vegetables = pd.read_csv('vegetables.csv')

packages = ["20","30", "18", "16"]

df.insert(2, "Packages", packages, True)

print(df)

#I know this isn't right and I don't know why it's doing this. I used batches earlier and everything I ran the code it kept creating more columns 
#I deleted it and wanted to use packages thinking that it would delete permanently but batches is still there for some reason

   Unnamed: 0  Batches Packages Packages Packages  Batches  Batches  Batches  \
0           0       14       20       20       20       14       14       14   
1           1       23       30       30       30       23       23       23   
2           2       18       18       18       18       18       18       18   
3           3       26       16       16       16       26       26       26   

   Batches  Batches  Batches  Batches  Batches Vegetable  Batches  Batches  \
0       14       14       14       14       14  Broccoli       14       14   
1       23       23       23       23       23   Carrots       23       23   
2       18       18       18       18       18     Beets       18       18   
3       26       26       26       26       26    Squash       26       26   

   Batches   Color  Batches  
0       14   Green       23  
1       23  Orange       11  
2       18  Purple       14  
3       26  Yellow       10  
